import Link from 'next/link'
import { faqs, services, site, zones } from '@/data/site'

type Theme = { mode: number; ink: string; paper: string; accent: string; muted: string; label: string }

const themes: Record<string, Theme> = {
  Catania: { mode: 0, ink: '#17100d', paper: '#f6efe3', accent: '#ef5b2a', muted: '#f5bd76', label: 'Sicilia operativa' },
  Livorno: { mode: 1, ink: '#103b55', paper: '#f6fbfd', accent: '#177eb5', muted: '#ccebf3', label: 'Costa e viabilità' },
  Napoli: { mode: 2, ink: '#24191b', paper: '#fff7ee', accent: '#d5333e', muted: '#f7d2ba', label: 'Mobilità urbana' },
  Padova: { mode: 3, ink: '#102d2b', paper: '#f2f7f3', accent: '#157a63', muted: '#c8e8d8', label: 'Assistenza tecnica' },
  Prato: { mode: 4, ink: '#30241f', paper: '#fbf5ec', accent: '#b75325', muted: '#f0d1ad', label: 'Interventi sul territorio' },
  Salerno: { mode: 5, ink: '#263933', paper: '#f7f5eb', accent: '#d06e42', muted: '#f2d5b8', label: 'Strade e provincia' },
  Pescara: { mode: 6, ink: '#082943', paper: '#f3f9fc', accent: '#00a6c8', muted: '#bee9ef', label: 'Assistenza in movimento' },
  Latina: { mode: 7, ink: '#193024', paper: '#f4f8ee', accent: '#6b9d2d', muted: '#dcebb8', label: 'Pronto intervento' },
  Trieste: { mode: 8, ink: '#1c2733', paper: '#f4f5f6', accent: '#526f88', muted: '#d6e0e6', label: 'Viabilità del nord-est' },
}

const heroImages: Record<string, string> = {
  Catania: '/images/hero-catania-original.png', Livorno: '/images/hero-livorno-original.png', Napoli: '/images/hero-napoli-original.png', Padova: '/images/hero-padova-original.png', Prato: '/images/hero-prato-original.png', Salerno: '/images/hero-salerno-original.png', Pescara: '/images/hero-pescara-original.png', Latina: '/images/hero-latina-original.png', Trieste: '/images/hero-trieste-original.png',
}
const logos: Record<string, string> = {
  Catania: '/images/brand-catania.png', Livorno: '/images/brand-livorno.png', Napoli: '/images/brand-napoli.png', Padova: '/images/brand-padova.png', Prato: '/images/brand-prato.png', Salerno: '/images/brand-salerno.png', Pescara: '/images/brand-pescara.png', Latina: '/images/brand-latina.png', Trieste: '/images/brand-trieste.png',
}

function phoneHref() { return `tel:${site.tel}` }

export default function CityHome() {
  const theme = themes[site.city] || themes.Catania
  const image = heroImages[site.city] || '/images/home-hero.jpg'
  const logo = logos[site.city]
  const zoneItems = (zones as unknown as Array<string | { name: string; slug: string }>).map((zone) => typeof zone === 'string' ? { name: zone, slug: zone.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '') } : zone)
  const faqItems = (faqs as unknown as Array<{ question: string; answer: string } | [string, string]>).map((faq) => Array.isArray(faq) ? { question: faq[0], answer: faq[1] } : faq)
  const paragraphs = [
    <p key="a"><strong>Un veicolo fermo cambia immediatamente i programmi.</strong> Può accadere mentre stai andando al lavoro, durante un rientro serale, vicino a casa o lungo una strada che non conosci bene. In quei minuti non serve una risposta generica: serve capire dove ti trovi, che mezzo hai, quale problema stai vedendo e se il veicolo può essere movimentato senza rischi. Il nostro servizio di carroattrezzi a {site.city} nasce per rendere questo passaggio più semplice, con una conversazione diretta e indicazioni comprensibili.</p>,
    <p key="b">La richiesta parte sempre dalla situazione reale. Una batteria scarica in un parcheggio non è un’auto danneggiata dopo un sinistro; una moto non va fissata come una vettura; un furgone con materiale di lavoro richiede attenzioni diverse da un’utilitaria. Raccogliere i dettagli prima di muovere il mezzo permette di preparare un recupero coerente, senza trasformare l’urgenza in una sequenza di telefonate ripetute o spiegazioni contraddittorie.</p>,
    <p key="c"><strong>La destinazione è già parte della soluzione.</strong> Officina di fiducia, carrozzeria, abitazione, deposito o altro indirizzo concordato: stabilire dove deve arrivare il veicolo aiuta a organizzare l’intervento con maggiore precisione. Molte persone scoprono troppo tardi quanto questa decisione incida sulla tranquillità della giornata. Definirla prima evita di rimanere con il mezzo caricato e una scelta ancora da fare.</p>,
    <p key="d">Nelle strade urbane, nelle zone produttive, vicino a un’uscita o lungo un collegamento extraurbano, il contesto cambia velocemente. Per questo non trattiamo ogni chiamata come se fosse uguale alla precedente. La posizione, la direzione di marcia quando serve, lo spazio disponibile e le condizioni di sicurezza sono elementi concreti. Comunicarli in modo ordinato permette di dare al recupero una base solida fin dall’inizio.</p>,
    <p key="e"><strong>La rapidità ha valore quando resta lucida.</strong> Essere veloci non significa arrivare senza informazioni o scegliere la strada più semplice soltanto per chi interviene. Significa ridurre l’attesa raccogliendo subito ciò che conta e preparando il mezzo adeguato. Quando l’auto non parte, quando compare una spia importante o quando il veicolo non è più sicuro da guidare, avere un riferimento chiaro fa la differenza.</p>,
    <p key="f">Il carroattrezzi non è solo il passaggio finale dopo un guasto. È un servizio che accompagna una decisione: spostare il mezzo nel modo corretto, proteggerlo durante il carico e portarlo nel punto in cui potrà essere controllato o riparato. Per questo ti chiediamo informazioni semplici, senza complicare la chiamata. Più il quadro è chiaro, più il recupero può essere organizzato con cura.</p>,
    <p key="g"><strong>Auto, moto, scooter e veicoli commerciali meritano la stessa attenzione, ma non lo stesso metodo.</strong> Le due ruote hanno bisogno di fissaggi specifici. Un’auto incidentata può richiedere una valutazione prudente prima del carico. Un furgone fermo può avere vincoli di peso, attrezzatura o destinazione. Spiegare il mezzo e il problema consente di orientare il servizio senza lasciare nulla all’improvvisazione.</p>,
    <p key="h">Anche nei casi apparentemente semplici è utile fermarsi un momento e valutare. Una gomma danneggiata, un’avaria elettronica, un problema all’avviamento o una perdita di potenza possono avere conseguenze diverse. Non è necessario fare diagnosi al telefono: basta descrivere quello che sta succedendo. Da lì si può capire se la priorità è un supporto immediato, un recupero completo o un trasferimento verso un tecnico.</p>,
    <p key="i"><strong>Il territorio di {site.city} ha ritmi e percorsi diversi.</strong> Ci sono aree centrali, strade periferiche, ingressi industriali, collegamenti di provincia e punti in cui attendere può essere più scomodo. Una posizione condivisa o un riferimento visibile aiutano molto, ma resta importante anche raccontare se il veicolo è in carreggiata, in un parcheggio, in una proprietà privata o in un punto con poco spazio di manovra.</p>,
    <p key="j">Un’assistenza fatta bene non alimenta l’ansia di chi chiama. Restituisce ordine: chiarisce cosa comunicare, quale può essere il passaggio successivo e dove andrà il veicolo. L’imprevisto resta un imprevisto, ma non deve prendere il controllo dell’intera giornata. Con informazioni utili, un mezzo adatto e una destinazione definita, il recupero diventa finalmente una cosa concreta da risolvere.</p>,
  ]

  const call = <Link href={phoneHref()} className="inline-flex shrink-0 items-center justify-center gap-2.5 rounded-xl px-5 py-3 text-sm font-black tracking-[.025em] text-white shadow-[0_12px_24px_rgba(0,0,0,.16)] transition duration-200 hover:-translate-y-0.5 hover:shadow-[0_18px_30px_rgba(0,0,0,.2)]" style={{ background: theme.accent }}><span className="opacity-85">Chiama ora</span><span className="h-4 w-px bg-white/45" /><span className="whitespace-nowrap">{site.phone}</span></Link>
  const headerCall = <Link href={phoneHref()} className="inline-flex shrink-0 items-center justify-center gap-2.5 rounded-xl px-5 py-3 text-sm font-black tracking-[.025em] text-white shadow-[0_12px_24px_rgba(0,0,0,.16)] transition duration-200 hover:-translate-y-0.5 hover:shadow-[0_18px_30px_rgba(0,0,0,.2)]" style={{ background: theme.accent }}><span>Chiama ora</span><span className="hidden h-4 w-px bg-white/45 sm:block" /><span className="hidden whitespace-nowrap sm:inline">{site.phone}</span></Link>
  const title = <>Carroattrezzi a {site.city}.<br />Una risposta utile, quando l’auto si ferma.</>
  const narrative = paragraphs.map((paragraph, index) => <article key={index} className="border-t-2 border-black/10 pt-5"><span className="text-xs font-black uppercase tracking-[.18em]" style={{ color: theme.accent }}>Punto {String(index + 1).padStart(2, '0')}</span><div className="mt-3">{paragraph}</div></article>)

  return <main className="min-h-screen overflow-x-hidden" style={{ background: theme.paper, color: theme.ink }}>
    <header className="sticky top-0 z-40 border-b border-black/10 bg-white/95 backdrop-blur"><div className="mx-auto flex min-h-[80px] max-w-[1480px] items-center justify-between gap-3 px-5 lg:gap-5 lg:px-10"><Link href="/" className="flex min-w-0 items-center gap-2.5"><img src={logo} alt="" className="h-10 w-10 shrink-0 object-contain sm:h-12 sm:w-12" /><span className="min-w-0 text-[10px] font-black uppercase leading-tight tracking-[.11em] sm:text-xs sm:tracking-[.14em]">Carroattrezzi<br /><span style={{ color: theme.accent }}>{site.city}</span></span></Link><nav className="hidden gap-7 text-sm font-bold text-slate-600 lg:flex"><a href="#servizi">Servizi</a><a href="#metodo">Metodo</a><a href="#zone">Zone</a><a href="#faq">FAQ</a></nav>{headerCall}</div></header>

    {theme.mode === 0 && <section className="relative isolate overflow-hidden bg-[#17100d] px-5 py-24 text-white lg:px-10 lg:py-40"><img src={image} alt={`Carroattrezzi in intervento a ${site.city}`} className="absolute inset-0 -z-10 h-full w-full object-cover opacity-35" /><div className="mx-auto max-w-[1480px]"><div className="w-[calc(100vw-2.5rem)] max-w-3xl min-w-0 rounded-[2.5rem] border border-white/15 bg-[#17100d]/85 p-8 backdrop-blur sm:w-full sm:p-14"><p className="break-words text-xs font-black uppercase tracking-[.25em]" style={{ color: theme.muted }}>{theme.label} · 24 ore</p><h1 className="mt-6 max-w-full break-words text-[clamp(2.65rem,11.5vw,4.5rem)] font-black leading-[.92] tracking-[-.06em]">{title}</h1><p className="mt-7 max-w-2xl break-words text-lg leading-8 text-slate-200">Dalla posizione alla destinazione: gestiamo il recupero con indicazioni chiare, senza lasciare la situazione in sospeso.</p><div className="mt-11">{call}</div></div></div></section>}
    {theme.mode === 1 && <section className="px-5 py-16 lg:px-10 lg:py-28"><div className="mx-auto grid max-w-[1480px] gap-12 lg:grid-cols-[.85fr_1.15fr] lg:items-end"><div><p className="text-xs font-black uppercase tracking-[.25em]" style={{ color: theme.accent }}>{theme.label}</p><h1 className="mt-6 text-5xl font-black leading-[.92] tracking-[-.06em] sm:text-7xl">{title}</h1><p className="mt-7 text-lg leading-8 text-slate-600">Il recupero parte da una richiesta chiara. Ci dici cosa succede, dove sei e dove deve arrivare il veicolo.</p><div className="mt-11">{call}</div></div><img src={image} alt={`Soccorso stradale a ${site.city}`} className="h-[420px] w-full rounded-[3rem] object-cover shadow-2xl lg:h-[650px]" /></div></section>}
    {theme.mode === 2 && <section className="grid min-h-[650px] lg:grid-cols-2"><div className="flex flex-col justify-center px-5 py-20 lg:px-[max(40px,calc((100vw-1480px)/2))]"><p className="text-xs font-black uppercase tracking-[.25em]" style={{ color: theme.accent }}>{theme.label}</p><h1 className="mt-6 max-w-3xl text-5xl font-black leading-[.92] tracking-[-.06em] sm:text-7xl">{title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-600">Un riferimento concreto per guasti, recuperi e trasporti verso la destinazione che scegli tu.</p><div className="mt-11">{call}</div></div><img src={image} alt={`Carroattrezzi a ${site.city}`} className="h-full min-h-[420px] w-full object-cover" /></section>}
    {theme.mode === 3 && <section className="px-5 py-16 lg:px-10 lg:py-24"><div className="mx-auto max-w-[1480px]"><div className="grid gap-5 lg:grid-cols-[.6fr_1.4fr]"><div className="p-7" style={{ background: theme.ink, color: '#fff' }}><p className="text-xs font-black uppercase tracking-[.25em]" style={{ color: theme.muted }}>{theme.label}</p><p className="mt-16 text-2xl font-black">24 ore, una richiesta alla volta.</p></div><div><img src={image} alt={`Assistenza con carroattrezzi a ${site.city}`} className="h-72 w-full object-cover lg:h-[450px]" /></div></div><div className="mt-10 max-w-4xl"><h1 className="text-5xl font-black leading-[.92] tracking-[-.06em] sm:text-7xl">{title}</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-600">Capire cosa serve prima di muovere il mezzo è il modo più serio di ridurre tempi persi e passaggi inutili.</p><div className="mt-11">{call}</div></div></div></section>}
    {theme.mode === 4 && <section className="px-5 py-16 lg:px-10 lg:py-28"><div className="mx-auto grid max-w-[1480px] gap-10 lg:grid-cols-[1.25fr_.75fr]"><div className="border-l-[10px] pl-6" style={{ borderColor: theme.accent }}><p className="text-xs font-black uppercase tracking-[.25em]" style={{ color: theme.accent }}>{theme.label}</p><h1 className="mt-6 text-5xl font-black leading-[.92] tracking-[-.06em] sm:text-7xl">{title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-600">Per auto, moto e furgoni fermi: informazioni corrette, recupero ordinato, destinazione concordata.</p><div className="mt-11">{call}</div></div><div className="self-end"><img src={image} alt={`Carroattrezzi pronto all’intervento a ${site.city}`} className="h-[440px] w-full rounded-t-[7rem] object-cover" /></div></div></section>}
    {theme.mode === 5 && <section className="px-5 py-16 lg:px-10 lg:py-24" style={{ background: theme.muted }}><div className="mx-auto grid max-w-[1480px] gap-10 lg:grid-cols-[.75fr_1.25fr]"><img src={image} alt={`Soccorso stradale a ${site.city}`} className="h-[420px] w-full rounded-[2.5rem] object-cover" /><div className="flex flex-col justify-center"><p className="text-xs font-black uppercase tracking-[.25em]" style={{ color: theme.accent }}>{theme.label}</p><h1 className="mt-6 text-5xl font-black leading-[.92] tracking-[-.06em] sm:text-7xl">{title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-700">Ti aiutiamo a scegliere il passo successivo, senza confusione e con un veicolo caricato in modo corretto.</p><div className="mt-11">{call}</div></div></div></section>}
    {theme.mode === 6 && <section className="bg-[#082943] px-5 py-20 text-white lg:px-10 lg:py-28"><div className="mx-auto grid max-w-[1480px] gap-10 lg:grid-cols-[1fr_.85fr]"><div><p className="text-xs font-black uppercase tracking-[.25em]" style={{ color: theme.muted }}>{theme.label}</p><h1 className="mt-6 text-5xl font-black leading-[.92] tracking-[-.06em] sm:text-7xl">{title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-200">Un guasto non deve diventare una giornata intera di incertezza. Raccogliamo ciò che serve e organizziamo il recupero.</p><div className="mt-11">{call}</div></div><div className="border-8 border-white/15 p-3"><img src={image} alt={`Carroattrezzi operativo a ${site.city}`} className="h-[420px] w-full object-cover" /></div></div></section>}
    {theme.mode === 7 && <section className="px-5 py-16 lg:px-10 lg:py-24"><div className="mx-auto max-w-[1480px]"><div className="grid items-end gap-8 lg:grid-cols-[.65fr_1.35fr]"><div><p className="text-xs font-black uppercase tracking-[.25em]" style={{ color: theme.accent }}>{theme.label}</p><h1 className="mt-6 text-5xl font-black leading-[.92] tracking-[-.06em] sm:text-8xl">Carroattrezzi<br /><span style={{ color: theme.accent }}>a {site.city}</span></h1></div><img src={image} alt={`Intervento di soccorso stradale a ${site.city}`} className="h-72 w-full rounded-[2rem] object-cover lg:h-[440px]" /></div><div className="mt-10 max-w-3xl"><p className="text-xl leading-9 text-slate-600">Quando l’auto si ferma, sapere cosa fare è già metà della soluzione. Qui trovi un contatto diretto per organizzare il recupero con criterio.</p><div className="mt-8">{call}</div></div></div></section>}
    {theme.mode === 8 && <section className="px-5 py-16 lg:px-10 lg:py-28"><div className="mx-auto max-w-[1480px]"><p className="text-xs font-black uppercase tracking-[.25em]" style={{ color: theme.accent }}>{theme.label}</p><div className="mt-7 grid gap-10 lg:grid-cols-[1.2fr_.8fr]"><div><h1 className="text-5xl font-black leading-[.92] tracking-[-.06em] sm:text-8xl">{title}</h1><p className="mt-8 max-w-2xl text-lg leading-8 text-slate-600">Un servizio organizzato per auto ferme, moto, furgoni e veicoli che devono essere trasportati in sicurezza.</p><div className="mt-11">{call}</div></div><div className="border-t-4 pt-5" style={{ borderColor: theme.accent }}><img src={image} alt={`Carroattrezzi per Trieste e provincia`} className="h-[400px] w-full object-cover grayscale" /></div></div></div></section>}

    <section id="metodo" className="px-5 py-24 lg:px-10 lg:py-32"><div className="mx-auto grid max-w-[1480px] gap-12 lg:grid-cols-[.72fr_1.28fr]"><div><p className="text-xs font-black uppercase tracking-[.25em]" style={{ color: theme.accent }}>Un servizio da capire</p><h2 className="mt-5 text-4xl font-black leading-[.98] tracking-[-.05em] sm:text-6xl">Non una chiamata generica. Un recupero preparato bene.</h2></div><div className="grid gap-5 sm:grid-cols-3"><div className="border-t-4 pt-5" style={{ borderColor: theme.accent }}><strong className="text-3xl">01</strong><h3 className="mt-5 text-xl font-black">Raccogliamo</h3><p className="mt-3 leading-7 text-slate-600">Posizione, mezzo, problema e accesso alla zona.</p></div><div className="border-t-4 pt-5" style={{ borderColor: theme.accent }}><strong className="text-3xl">02</strong><h3 className="mt-5 text-xl font-black">Valutiamo</h3><p className="mt-3 leading-7 text-slate-600">Il tipo di recupero e le attenzioni necessarie.</p></div><div className="border-t-4 pt-5" style={{ borderColor: theme.accent }}><strong className="text-3xl">03</strong><h3 className="mt-5 text-xl font-black">Concordiamo</h3><p className="mt-3 leading-7 text-slate-600">La destinazione, prima di caricare il veicolo.</p></div></div></div></section>
    <section className="px-5 py-24 lg:px-10 lg:py-32" style={{ background: theme.muted }}><div className="mx-auto max-w-[1180px]"><p className="text-xs font-black uppercase tracking-[.25em]" style={{ color: theme.accent }}>Un aiuto concreto</p><h2 className="mt-5 max-w-4xl text-4xl font-black tracking-[-.05em] sm:text-6xl">Quando succede, avere un riferimento cambia la giornata.</h2><div className={`mt-12 text-lg leading-8 text-slate-700 ${theme.mode === 0 ? 'grid gap-8 lg:grid-cols-2' : theme.mode === 1 ? 'grid gap-x-14 gap-y-10 md:grid-cols-2' : theme.mode === 2 ? 'space-y-10' : theme.mode === 3 ? 'grid gap-6 md:grid-cols-3' : theme.mode === 4 ? 'grid gap-10 lg:grid-cols-[.7fr_1.3fr]' : theme.mode === 5 ? 'grid gap-8 sm:grid-cols-2' : theme.mode === 6 ? 'grid gap-6 md:grid-cols-2' : theme.mode === 7 ? 'space-y-8' : 'grid gap-8 lg:grid-cols-2'}`}>{narrative}</div></div></section>
    <section id="servizi" className="px-5 py-24 lg:px-10 lg:py-32" style={{ background: theme.ink, color: '#fff' }}><div className="mx-auto max-w-[1480px]"><p className="text-xs font-black uppercase tracking-[.25em]" style={{ color: theme.muted }}>Interventi dedicati</p><h2 className="mt-5 max-w-3xl text-4xl font-black tracking-[-.05em] sm:text-6xl">Ogni veicolo fermo merita il recupero più adatto.</h2><div className={`mt-12 ${theme.mode % 3 === 0 ? 'divide-y divide-white/15' : 'grid gap-4 md:grid-cols-2 xl:grid-cols-3'}`}>{services.map((service, index) => <Link key={service.slug} href={`/servizi/${service.slug}/`} className={`${theme.mode % 3 === 0 ? 'grid gap-4 py-7 md:grid-cols-[70px_1fr]' : 'rounded-[1.8rem] border border-white/15 bg-white/5 p-7'} transition hover:bg-white/10`}><span className="text-2xl font-black" style={{ color: theme.muted }}>0{index + 1}</span><div><h3 className="text-xl font-black">{service.title}</h3><p className="mt-3 text-sm leading-7 text-slate-300">{(service as { intro?: string; text?: string }).intro ?? (service as { text?: string }).text ?? 'Intervento organizzato con attenzione e comunicazioni chiare.'}</p></div></Link>)}</div></div></section>
    <section id="zone" className="px-5 py-24 lg:px-10 lg:py-32"><div className="mx-auto grid max-w-[1480px] gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-black uppercase tracking-[.25em]" style={{ color: theme.accent }}>Zone servite</p><h2 className="mt-5 text-4xl font-black tracking-[-.05em] sm:text-6xl">{site.city} e i comuni vicini.</h2><p className="mt-7 text-lg leading-8 text-slate-600">Apri la pagina della tua località per trovare un riferimento dedicato e preparare con semplicità le informazioni utili al recupero.</p></div><div className="grid gap-x-8 sm:grid-cols-2">{zoneItems.map((zone) => <Link key={zone.slug} href={`/zone/${zone.slug}/`} className="flex items-center justify-between border-b-2 border-black/10 py-5 text-lg font-black transition hover:px-3"><span>{zone.name}</span><span style={{ color: theme.accent }}>↗</span></Link>)}</div></div></section>
    <section id="faq" className="px-5 py-24 lg:px-10 lg:py-32" style={{ background: theme.muted }}><div className="mx-auto max-w-4xl"><p className="text-center text-xs font-black uppercase tracking-[.25em]" style={{ color: theme.accent }}>Domande frequenti</p><h2 className="mt-5 text-center text-4xl font-black tracking-[-.05em] sm:text-6xl">Le risposte prima della chiamata.</h2><div className="mt-12 divide-y-2 divide-black/10 border-y-2 border-black/10">{faqItems.map((faq) => <details key={faq.question} className="py-6"><summary className="cursor-pointer list-none text-xl font-black">{faq.question}</summary><p className="mt-4 leading-7 text-slate-700">{faq.answer}</p></details>)}</div></div></section>
    <section className="px-5 py-24 lg:px-10 lg:py-32" style={{ background: theme.accent, color: '#fff' }}><div className="mx-auto flex max-w-[1480px] flex-col justify-between gap-12 lg:flex-row lg:items-end"><div className="max-w-3xl"><p className="text-xs font-black uppercase tracking-[.25em] text-white/80">Veicolo fermo?</p><h2 className="mt-5 text-5xl font-black leading-[.94] tracking-[-.06em] sm:text-7xl">Raccontaci cosa succede. Da qui si riparte.</h2><p className="mt-6 text-lg leading-8 text-white/90">Comunica posizione, tipo di mezzo e destinazione. Ti aiutiamo a organizzare un recupero ordinato.</p></div><Link href={phoneHref()} className="inline-flex shrink-0 items-center justify-center gap-2.5 rounded-xl bg-white px-5 py-3.5 text-base font-black tracking-[.025em] shadow-[0_14px_28px_rgba(0,0,0,.18)] transition hover:-translate-y-0.5 hover:shadow-[0_20px_34px_rgba(0,0,0,.24)]" style={{ color: theme.ink }}><span>Chiama ora</span><span className="h-4 w-px bg-black/20" /><span className="whitespace-nowrap">{site.phone}</span></Link></div></section>
    <footer className="px-5 py-12 text-white lg:px-10" style={{ background: theme.ink }}><div className="mx-auto grid max-w-[1480px] gap-8 md:grid-cols-[1fr_auto_auto]"><div><strong className="text-xl">{site.name}</strong><p className="mt-3 max-w-md text-sm leading-6 text-slate-300">Soccorso stradale, recupero e trasporto veicoli con assistenza chiara sul territorio di {site.city}.</p></div><div className="text-sm text-slate-300"><p>{site.address}</p><p className="mt-1">{site.email}</p></div><Link href={phoneHref()} className="text-lg font-black" style={{ color: theme.muted }}>{site.phone}</Link></div></footer>
  </main>
}
