import Link from 'next/link'
import { faqs, services, site, zones } from '@/data/site'

const palettes: Record<string, { ink: string; paper: string; accent: string; soft: string }> = {
  keynote: { ink: '#0b1736', paper: '#f5f8ff', accent: '#155eef', soft: '#dbeafe' },
  spotlight: { ink: '#102c2b', paper: '#f4fffc', accent: '#008a78', soft: '#ccfbf1' },
  primer: { ink: '#18212b', paper: '#f7f8fa', accent: '#c2410c', soft: '#ffedd5' },
  protocol: { ink: '#20142d', paper: '#fff8fc', accent: '#be185d', soft: '#fce7f3' },
  pocket: { ink: '#20152d', paper: '#fffaff', accent: '#8b5cf6', soft: '#ede9fe' },
  syntax: { ink: '#092d24', paper: '#f3fff9', accent: '#087f5b', soft: '#d1fae5' },
  catalyst: { ink: '#292014', paper: '#fffdf5', accent: '#b7791f', soft: '#fef3c7' },
  salient: { ink: '#18202b', paper: '#f8fafc', accent: '#b42318', soft: '#fee2e2' },
  studio: { ink: '#17312f', paper: '#f7fffd', accent: '#0f766e', soft: '#ccfbf1' },
}

const palette = palettes[site.template] || palettes.salient
const heroImages: Record<string, string> = {
  Brescia: '/images/hero-towtruck.webp', Catania: '/images/hero-catania.jpg', Livorno: '/images/hero-livorno.jpg', Napoli: '/images/hero-napoli.jpg', Padova: '/images/hero-padova.jpg', Prato: '/images/hero-prato.jpg', Salerno: '/images/hero-salerno.jpg', Pescara: '/images/hero-pescara.jpg', Latina: '/images/hero-latina.jpg', Trieste: '/images/hero-trieste.jpg',
}
const logoImages: Record<string, string> = {
  Brescia: '/images/logo-brescia.png', Catania: '/images/logo-catania.png', Livorno: '/images/logo-livorno.png', Napoli: '/images/logo-napoli.png', Padova: '/images/logo-padova.png', Prato: '/images/logo-prato.png', Salerno: '/images/logo-salerno.png', Pescara: '/images/logo-pescara.png', Latina: '/images/logo-latina.png', Trieste: '/images/logo-trieste.png',
}

function Call({ children = `Chiama ${site.phone}`, light = false }: { children?: React.ReactNode; light?: boolean }) {
  return <Link href={`tel:${site.tel}`} className="inline-flex items-center justify-center rounded-full px-6 py-3.5 text-sm font-black transition hover:-translate-y-1" style={{ background: light ? '#fff' : palette.accent, color: light ? palette.ink : '#fff', boxShadow: light ? 'none' : `0 14px 30px ${palette.accent}44` }}>{children}</Link>
}

export default function ProprietaryHome() {
  const darkHero = ['keynote', 'pocket', 'syntax'].includes(site.template)
  const zoneItems = (zones as unknown as Array<string | { name: string; slug: string }>).map((zone) => typeof zone === 'string' ? { name: zone, slug: zone.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '') } : zone)
  const faqItems = (faqs as unknown as Array<{ question: string; answer: string } | [string, string]>).map((faq) => Array.isArray(faq) ? { question: faq[0], answer: faq[1] } : faq)
  const heroImage = heroImages[site.city] || '/images/home-hero.jpg'
  const logoImage = logoImages[site.city]
  return <div className="min-h-screen" style={{ background: palette.paper, color: palette.ink }}>
    <header className="sticky top-0 z-30 border-b border-black/10 bg-white/90 backdrop-blur"><div className="mx-auto flex min-h-[76px] max-w-7xl items-center justify-between gap-6 px-5 lg:px-8"><Link href="/" className="flex items-center gap-3"><span className="flex h-12 w-32 items-center justify-start overflow-hidden"><img src={logoImage} alt={site.name} className="max-h-12 w-auto object-contain" /></span></Link><nav className="hidden gap-7 text-sm font-bold text-slate-600 lg:flex"><a href="#servizi">Servizi</a><a href="#territorio">Zone servite</a><a href="#faq">FAQ</a></nav><Call>Chiama 24H</Call></div></header>
    <main>
      <section className="relative overflow-hidden px-5 py-16 sm:py-24 lg:px-8 lg:py-32" style={{ background: darkHero ? palette.ink : palette.soft, color: darkHero ? '#fff' : palette.ink }}><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[1.05fr_.95fr]"><div><p className="text-xs font-black uppercase tracking-[.24em]" style={{ color: darkHero ? palette.soft : palette.accent }}>Soccorso stradale · {site.city} · 24 ore</p><h1 className="mt-6 max-w-4xl text-5xl font-black leading-[.96] tracking-[-.06em] sm:text-7xl lg:text-8xl">Carroattrezzi a {site.city}</h1><p className="mt-7 max-w-2xl text-lg leading-8" style={{ color: darkHero ? '#dbe4f2' : '#475569' }}>Quando il veicolo si ferma, la priorità è capire rapidamente cosa serve. Raccogliamo posizione, tipo di mezzo, problema e destinazione, poi organizziamo il recupero con un approccio concreto e comprensibile.</p><div className="mt-9 flex flex-wrap gap-3"><Call /><Link href="#servizi" className="inline-flex items-center rounded-full border px-6 py-3.5 text-sm font-black" style={{ borderColor: darkHero ? '#ffffff55' : '#0002', color: darkHero ? '#fff' : palette.ink }}>Vedi gli interventi</Link></div><div className="mt-12 grid max-w-xl grid-cols-3 gap-4 border-t pt-6 text-sm" style={{ borderColor: darkHero ? '#ffffff2b' : '#0002' }}><div><strong className="block text-2xl">24H</strong><span style={{ color: darkHero ? '#cbd5e1' : '#64748b' }}>disponibilità</span></div><div><strong className="block text-2xl">1</strong><span style={{ color: darkHero ? '#cbd5e1' : '#64748b' }}>contatto diretto</span></div><div><strong className="block text-2xl">{site.city}</strong><span style={{ color: darkHero ? '#cbd5e1' : '#64748b' }}>e provincia</span></div></div></div><div className="relative"><div className="overflow-hidden rounded-[2rem] border-[10px] border-white bg-white shadow-2xl"><img src={heroImage} alt={`Carroattrezzi in intervento a ${site.city}`} className="h-[360px] w-full object-cover sm:h-[520px]" /></div><div className="absolute -bottom-5 left-5 max-w-[250px] rounded-2xl bg-white p-5 text-slate-900 shadow-xl"><strong className="block text-sm">Richiesta gestita con chiarezza</strong><span className="mt-1 block text-xs leading-5 text-slate-600">Dalla posizione alla destinazione, senza passaggi inutili.</span></div></div></div></section>
      <section className="px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-xs font-black uppercase tracking-[.22em]" style={{ color: palette.accent }}>Quando succede davvero</p><h2 className="mt-4 text-4xl font-black tracking-[-.05em] sm:text-6xl">Il problema è già abbastanza complicato. La richiesta non deve esserlo.</h2><p className="mt-6 text-lg leading-8 text-slate-600">Un guasto può arrivare davanti casa, in tangenziale, in un parcheggio o durante un viaggio. In ogni caso è utile parlare con una struttura che sappia distinguere un traino da un recupero complesso e una batteria scarica da un veicolo che non è sicuro da movimentare.</p></div><div className="grid gap-5 sm:grid-cols-2"><article className="rounded-3xl bg-white p-7 shadow-[0_20px_55px_rgba(15,23,42,.08)]"><span className="text-4xl font-black" style={{ color: palette.accent }}>01</span><h3 className="mt-7 text-2xl font-black">Capire prima di muovere il mezzo</h3><p className="mt-3 leading-7 text-slate-600">Posizione, accesso, dimensioni, danni e destinazione definiscono il tipo di intervento. Più le informazioni sono chiare, più è semplice preparare la risposta corretta.</p></article><article className="rounded-3xl p-7" style={{ background: palette.soft }}><span className="text-4xl font-black" style={{ color: palette.accent }}>02</span><h3 className="mt-7 text-2xl font-black">Restituire ordine alla situazione</h3><p className="mt-3 leading-7 text-slate-700">Ti aiutiamo a ridurre telefonate ripetute, indicazioni confuse e destinazioni improvvisate. Il recupero viene spiegato con parole semplici, prima di procedere.</p></article></div></div></section>
      <section id="servizi" className="px-5 py-20 lg:px-8 lg:py-28" style={{ background: palette.ink, color: '#fff' }}><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><p className="text-xs font-black uppercase tracking-[.22em]" style={{ color: palette.soft }}>Interventi disponibili</p><h2 className="mt-4 text-4xl font-black tracking-[-.05em] sm:text-6xl">Un servizio diverso per ogni modo in cui il veicolo può fermarsi.</h2><p className="mt-6 text-lg leading-8 text-slate-300">Non esiste un solo tipo di soccorso. Per questo trovi pagine dedicate a traino, recupero, batteria, moto, furgoni e situazioni dopo un incidente.</p></div><div className="mt-12 grid gap-px overflow-hidden rounded-3xl bg-white/20 md:grid-cols-2 lg:grid-cols-3">{services.map((service, index) => <Link key={service.slug} href={`/servizi/${service.slug}/`} className="group bg-white/[.06] p-6 transition hover:bg-white/[.14]"><div className="flex items-center justify-between"><span className="text-xs font-black" style={{ color: palette.soft }}>0{index + 1}</span><span className="text-xl transition group-hover:translate-x-1" style={{ color: palette.soft }}>↗</span></div><h3 className="mt-10 text-xl font-black text-white">{service.title}</h3><p className="mt-3 text-sm leading-7 text-slate-300">{((service as { text?: string; intro?: string }).text ?? (service as { intro?: string }).intro ?? 'Intervento organizzato con attenzione, chiarezza e il mezzo più adatto alla situazione.')}</p></Link>)}</div></div></section>
      <section className="px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><div className="grid gap-10 lg:grid-cols-[1fr_1fr]"><div><p className="text-xs font-black uppercase tracking-[.22em]" style={{ color: palette.accent }}>Un territorio reale</p><h2 className="mt-4 text-4xl font-black tracking-[-.05em] sm:text-6xl">{site.city} e le località vicine.</h2><p className="mt-6 text-lg leading-8 text-slate-600">Le condizioni cambiano da una strada all’altra. Una zona industriale, un centro urbano, una provinciale o una strada stretta richiedono indicazioni diverse. Per questo puoi aprire la pagina della tua località e trovare un riferimento dedicato.</p><div className="mt-8"><Call>Parla con noi</Call></div></div><div id="territorio" className="grid gap-3 sm:grid-cols-2">{zoneItems.map((zone, index) => <Link key={zone.slug} href={`/zone/${zone.slug}/`} className="flex items-center justify-between border-b-2 px-2 py-4 text-base font-black transition hover:px-4" style={{ borderColor: index % 2 ? `${palette.accent}33` : `${palette.accent}66` }}><span>{zone.name}</span><span style={{ color: palette.accent }}>↗</span></Link>)}</div></div></div></section>
      <section id="faq" className="px-5 py-20 lg:px-8 lg:py-28" style={{ background: palette.soft }}><div className="mx-auto max-w-4xl"><p className="text-center text-xs font-black uppercase tracking-[.22em]" style={{ color: palette.accent }}>Domande frequenti</p><h2 className="mt-4 text-center text-4xl font-black tracking-[-.05em] sm:text-6xl">Prima di chiamare, le risposte che servono davvero.</h2><div className="mt-12 divide-y border-y border-black/15">{faqItems.map((faq) => <details key={faq.question} className="py-6"><summary className="cursor-pointer list-none text-lg font-black">{faq.question}</summary><p className="mt-4 max-w-3xl leading-7 text-slate-700">{faq.answer}</p></details>)}</div></div></section>
      <section className="px-5 py-24 text-center lg:px-8 lg:py-36" style={{ background: palette.accent, color: '#fff' }}><div className="mx-auto max-w-4xl"><h2 className="text-5xl font-black tracking-[-.06em] sm:text-7xl">Il veicolo è fermo a {site.city}?</h2><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-white/90">Raccontaci cosa è successo e dove ti trovi. Ti aiutiamo a trasformare un momento scomodo in un intervento chiaro, con il mezzo adatto e una destinazione concordata.</p><div className="mt-9"><Call light>Chiama {site.phone}</Call></div></div></section>
    </main>
    <footer className="border-t border-black/10 bg-white px-5 py-10 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-5 text-sm text-slate-600 sm:flex-row"><div><strong className="text-slate-950">{site.name}</strong><p className="mt-2">{site.address}</p><p className="mt-1">{site.email}</p></div><Link href={`tel:${site.tel}`} className="font-black" style={{ color: palette.accent }}>{site.phone}</Link></div></footer>
  </div>
}
