import Link from 'next/link'
import { faqs, services, site, zones } from '@/data/site'

type Palette = { ink: string; paper: string; accent: string; soft: string }

const palettes: Record<string, Palette> = {
  keynote: { ink: '#0b1736', paper: '#f5f8ff', accent: '#155eef', soft: '#dbeafe' },
  spotlight: { ink: '#102c2b', paper: '#f4fffc', accent: '#008a78', soft: '#ccfbf1' },
  primer: { ink: '#18212b', paper: '#f7f8fa', accent: '#c2410c', soft: '#ffedd5' },
  protocol: { ink: '#20142d', paper: '#fff8fc', accent: '#be185d', soft: '#fce7f3' },
  pocket: { ink: '#20152d', paper: '#fffaff', accent: '#8b5cf6', soft: '#ede9fe' },
  syntax: { ink: '#092d24', paper: '#f3fff9', accent: '#087f5b', soft: '#d1fae5' },
  catalyst: { ink: '#292014', paper: '#fffdf5', accent: '#b7791f', soft: '#fef3c7' },
  salient: { ink: '#18202b', paper: '#f8fafc', accent: '#b42318', soft: '#fee2e2' },
  studio: { ink: '#17312f', paper: '#f7fffd', accent: '#0f766e', soft: '#ccfbf1' },
}

const heroImages: Record<string, string> = {
  Brescia: '/images/hero-towtruck.webp', Catania: '/images/hero-catania.jpg', Livorno: '/images/hero-livorno.jpg', Napoli: '/images/hero-napoli.jpg', Padova: '/images/hero-padova.jpg', Prato: '/images/hero-prato.jpg', Salerno: '/images/hero-salerno.jpg', Pescara: '/images/hero-pescara.jpg', Latina: '/images/hero-latina.jpg', Trieste: '/images/hero-trieste.jpg',
}

const logoImages: Record<string, string> = {
  Brescia: '/images/logo-brescia.png', Catania: '/images/logo-catania.png', Livorno: '/images/logo-livorno.png', Napoli: '/images/logo-napoli.png', Padova: '/images/logo-padova.png', Prato: '/images/logo-prato.png', Salerno: '/images/logo-salerno.png', Pescara: '/images/logo-pescara.png', Latina: '/images/logo-latina.png', Trieste: '/images/logo-trieste.png',
}

function Call({ palette, children = `Chiama ${site.phone}`, light = false }: { palette: Palette; children?: React.ReactNode; light?: boolean }) {
  return <Link href={`tel:${site.tel}`} className="inline-flex items-center justify-center rounded-full px-6 py-3.5 text-sm font-black transition hover:-translate-y-1" style={{ background: light ? '#fff' : palette.accent, color: light ? palette.ink : '#fff', boxShadow: light ? 'none' : `0 14px 30px ${palette.accent}44` }}>{children}</Link>
}

function ServiceCards({ palette, services, dark = false, mode = 0 }: { palette: Palette; services: ReadonlyArray<any>; dark?: boolean; mode?: number }) {
  const card = (service: any, index: number, className: string) => <Link key={service.slug} href={`/servizi/${service.slug}/`} className={`group transition hover:-translate-y-1 ${className}`} style={{ background: dark ? 'rgba(255,255,255,.07)' : '#fff', borderColor: dark ? 'rgba(255,255,255,.16)' : `${palette.accent}33`, color: dark ? '#fff' : palette.ink }}><div className="flex items-center justify-between"><span className="text-xs font-black" style={{ color: palette.accent }}>0{index + 1}</span><span className="text-xl transition group-hover:translate-x-1" style={{ color: palette.accent }}>↗</span></div><h3 className="mt-5 text-xl font-black">{service.title}</h3><p className={`mt-3 text-sm leading-7 ${dark ? 'text-slate-300' : 'text-slate-600'}`}>{service.text ?? service.intro ?? 'Intervento organizzato con attenzione, chiarezza e il mezzo più adatto.'}</p></Link>
  if (mode === 1) return <div className="divide-y-2" style={{ borderColor: 'rgba(255,255,255,.18)' }}>{services.map((service, index) => card(service, index, 'grid gap-4 py-7 md:grid-cols-[80px_1fr]'))}</div>
  if (mode === 2) return <div className="grid gap-3 sm:grid-cols-2">{services.map((service, index) => card(service, index, index === 0 ? 'rounded-[2rem] border-4 p-8 sm:col-span-2' : 'rounded-2xl border p-6'))}</div>
  if (mode === 3) return <div className="grid gap-0 md:grid-cols-2">{services.map((service, index) => card(service, index, 'border-b border-r p-7'))}</div>
  if (mode === 4) return <div className="grid gap-6 lg:grid-cols-[1.25fr_.75fr]">{services.map((service, index) => card(service, index, index % 3 === 0 ? 'rounded-[2rem] border p-8 lg:row-span-2' : 'rounded-2xl border p-6'))}</div>
  return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{services.map((service, index) => card(service, index, 'rounded-[1.75rem] border p-7'))}</div>
}

export default function ProprietaryHome() {
  const palette = palettes[site.template] || palettes.salient
  const city = site.city
  const variant = ['Brescia', 'Catania', 'Livorno', 'Napoli', 'Padova', 'Prato', 'Salerno', 'Pescara', 'Latina', 'Trieste'].indexOf(city) % 5
  const heroImage = heroImages[city] || '/images/home-hero.jpg'
  const logoImage = logoImages[city]
  const zoneItems = (zones as unknown as Array<string | { name: string; slug: string }>).map((zone) => typeof zone === 'string' ? { name: zone, slug: zone.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '') } : zone)
  const faqItems = (faqs as unknown as Array<{ question: string; answer: string } | [string, string]>).map((faq) => Array.isArray(faq) ? { question: faq[0], answer: faq[1] } : faq)
  const heroCopy = <><p className="text-xs font-black uppercase tracking-[.24em]" style={{ color: palette.accent }}>Soccorso stradale · {city} · 24 ore</p><h1 className="mt-5 text-5xl font-black leading-[.95] tracking-[-.06em] sm:text-7xl">Carroattrezzi a {city}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">Quando il veicolo si ferma, raccogliamo posizione, tipo di mezzo e problema per organizzare un intervento concreto. Ti aiutiamo a passare dall’urgenza a una soluzione chiara, con una destinazione concordata prima del recupero.</p><div className="mt-8 flex flex-wrap gap-3"><Call palette={palette} /><Link href="#servizi" className="rounded-full border-2 px-6 py-3.5 text-sm font-black" style={{ borderColor: `${palette.accent}55` }}>Vedi gli interventi</Link></div></>
  return <div className="min-h-screen overflow-hidden" style={{ background: palette.paper, color: palette.ink }}>
    <header className="sticky top-0 z-30 border-b border-black/10 bg-white/95 backdrop-blur"><div className="mx-auto flex min-h-[78px] max-w-7xl items-center justify-between gap-5 px-5 lg:px-8"><Link href="/" className="flex h-12 w-40 items-center overflow-hidden"><img src={logoImage} alt={site.name} className="max-h-12 w-auto object-contain" /></Link><nav className="hidden gap-7 text-sm font-bold text-slate-600 lg:flex"><a href="#servizi">Servizi</a><a href="#territorio">Zone servite</a><a href="#faq">FAQ</a></nav><Call palette={palette}>Chiama 24H</Call></div></header>
    <main>
      {variant === 0 && <section className="px-5 py-16 lg:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.92fr_1.08fr] lg:items-center"><div>{heroCopy}<div className="mt-12 grid grid-cols-3 gap-3 border-t-2 pt-5 text-sm"><div><strong className="block text-2xl">24H</strong><span className="text-slate-500">sempre attivi</span></div><div><strong className="block text-2xl">1</strong><span className="text-slate-500">contatto diretto</span></div><div><strong className="block text-2xl">{city}</strong><span className="text-slate-500">e provincia</span></div></div></div><div className="relative"><img src={heroImage} alt={`Carroattrezzi in intervento a ${city}`} className="h-[430px] w-full rounded-[3rem] object-cover shadow-2xl lg:h-[610px]" /><div className="absolute -bottom-6 left-6 max-w-xs rounded-2xl bg-white p-5 shadow-xl"><strong className="block">Intervento organizzato</strong><span className="mt-1 block text-sm leading-6 text-slate-600">Dati chiari, mezzo adatto e destinazione concordata.</span></div></div></div></section>}
      {variant === 1 && <section className="relative px-5 py-24 lg:px-8 lg:py-40" style={{ background: palette.ink, color: '#fff' }}><div className="absolute inset-0 opacity-35"><img src={heroImage} alt="" className="h-full w-full object-cover" /></div><div className="relative mx-auto max-w-7xl"><div className="max-w-3xl rounded-[2.5rem] p-8 sm:p-14" style={{ background: `${palette.ink}e8` }}>{heroCopy}<div className="mt-9 flex items-center gap-5 text-sm text-slate-300"><span className="h-px w-12 bg-white/50" />Risposta concreta, senza passaggi inutili</div></div></div></section>}
      {variant === 2 && <section className="px-5 py-20 text-center lg:px-8 lg:py-32"><div className="mx-auto max-w-5xl"><div className="mx-auto mb-10 h-24 w-24 overflow-hidden rounded-full border-8 border-white shadow-xl"><img src={heroImage} alt={`Soccorso stradale a ${city}`} className="h-full w-full object-cover" /></div>{heroCopy}<div className="mx-auto mt-12 grid max-w-3xl gap-3 text-left sm:grid-cols-3"><div className="border-l-4 p-4" style={{ borderColor: palette.accent }}><strong>Capire</strong><p className="mt-2 text-sm text-slate-600">Posizione e problema prima di muovere il mezzo.</p></div><div className="border-l-4 p-4" style={{ borderColor: palette.accent }}><strong>Preparare</strong><p className="mt-2 text-sm text-slate-600">Il recupero giusto per auto, moto o furgone.</p></div><div className="border-l-4 p-4" style={{ borderColor: palette.accent }}><strong>Risolvere</strong><p className="mt-2 text-sm text-slate-600">Una destinazione concordata e nessuna confusione.</p></div></div></div></section>}
      {variant === 3 && <section className="px-5 py-16 lg:px-8 lg:py-24"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1.3fr_.7fr]"><div className="order-2 lg:order-1">{heroCopy}</div><aside className="order-1 lg:order-2"><img src={heroImage} alt={`Carroattrezzi a ${city}`} className="h-72 w-full rounded-2xl object-cover lg:h-[420px]" /><div className="mt-4 border-l-8 p-5" style={{ borderColor: palette.accent, background: palette.soft }}><strong className="text-lg">La priorità è ripartire con ordine.</strong><p className="mt-2 text-sm leading-6 text-slate-600">Dalla chiamata alla destinazione, sai sempre qual è il passaggio successivo.</p></div></aside></div></section>}
      {variant === 4 && <section className="px-5 py-16 lg:px-8 lg:py-24" style={{ background: palette.soft }}><div className="mx-auto max-w-7xl"><div className="grid items-end gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-xs font-black uppercase tracking-[.24em]" style={{ color: palette.accent }}>Assistenza locale</p><h1 className="mt-4 text-5xl font-black leading-none tracking-[-.06em] sm:text-8xl">Carroattrezzi<br /><span style={{ color: palette.accent }}>a {city}</span></h1></div><div><img src={heroImage} alt={`Soccorso stradale a ${city}`} className="h-72 w-full rounded-[2rem] object-cover lg:h-[390px]" />{heroCopy}</div></div></div></section>}
      <section className="px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><p className="text-xs font-black uppercase tracking-[.22em]" style={{ color: palette.accent }}>Quando succede davvero</p><h2 className="mt-4 text-4xl font-black tracking-[-.05em] sm:text-6xl">Il problema è già abbastanza complicato. La richiesta non deve esserlo.</h2><p className="mt-6 text-lg leading-8 text-slate-600">Un guasto può arrivare davanti casa, in tangenziale, in un parcheggio o durante un viaggio. Ti aiutiamo a distinguere un traino da un recupero complesso, una batteria scarica da un veicolo che non è sicuro da movimentare.</p></div><div className="mt-12 grid gap-5 lg:grid-cols-3"><article className="rounded-[2rem] bg-white p-7 shadow-xl"><strong className="text-4xl" style={{ color: palette.accent }}>01</strong><h3 className="mt-8 text-2xl font-black">Capire prima</h3><p className="mt-3 leading-7 text-slate-600">Posizione, accesso, dimensioni, danni e destinazione definiscono il servizio corretto.</p></article><article className="rounded-[2rem] p-7" style={{ background: palette.soft }}><strong className="text-4xl" style={{ color: palette.accent }}>02</strong><h3 className="mt-8 text-2xl font-black">Preparare bene</h3><p className="mt-3 leading-7 text-slate-700">Le informazioni raccolte permettono di organizzare il mezzo adatto alla situazione.</p></article><article className="rounded-[2rem] p-7 text-white" style={{ background: palette.ink }}><strong className="text-4xl" style={{ color: palette.soft }}>03</strong><h3 className="mt-8 text-2xl font-black">Risolvere senza confusione</h3><p className="mt-3 leading-7 text-slate-300">Concordiamo la destinazione e ti spieghiamo il passaggio successivo con parole semplici.</p></article></div></div></section>
      <section id="servizi" className="px-5 py-20 lg:px-8 lg:py-28" style={{ background: palette.ink, color: '#fff' }}><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div className="max-w-3xl"><p className="text-xs font-black uppercase tracking-[.22em]" style={{ color: palette.soft }}>Interventi disponibili</p><h2 className="mt-4 text-4xl font-black tracking-[-.05em] sm:text-6xl">Un servizio diverso per ogni veicolo fermo.</h2></div><Link href={`tel:${site.tel}`} className="font-black" style={{ color: palette.soft }}>Parla con un referente ↗</Link></div><div className="mt-12"><ServiceCards palette={palette} services={services} dark mode={variant} /></div></div></section>
      <section id="territorio" className="px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-black uppercase tracking-[.22em]" style={{ color: palette.accent }}>Un territorio reale</p><h2 className="mt-4 text-4xl font-black tracking-[-.05em] sm:text-6xl">{city} e le località vicine.</h2><p className="mt-6 text-lg leading-8 text-slate-600">Una strada urbana, una zona industriale o una provinciale richiedono indicazioni diverse. Per questo trovi un riferimento dedicato anche nei comuni vicini.</p><div className="mt-8"><Call palette={palette}>Parla con noi</Call></div></div><div className="grid gap-2 sm:grid-cols-2">{zoneItems.map((zone, index) => <Link key={zone.slug} href={`/zone/${zone.slug}/`} className="flex items-center justify-between border-b-2 px-3 py-5 font-black transition hover:px-5" style={{ borderColor: `${palette.accent}${index % 2 ? '33' : '66'}` }}><span>{zone.name}</span><span style={{ color: palette.accent }}>↗</span></Link>)}</div></div></section>
      <section id="faq" className="px-5 py-20 lg:px-8 lg:py-28" style={{ background: palette.soft }}><div className="mx-auto max-w-4xl"><p className="text-center text-xs font-black uppercase tracking-[.22em]" style={{ color: palette.accent }}>Domande frequenti</p><h2 className="mt-4 text-center text-4xl font-black tracking-[-.05em] sm:text-6xl">Le risposte che servono davvero.</h2><div className="mt-12 divide-y-2 border-y-2 border-black/10">{faqItems.map((faq) => <details key={faq.question} className="py-6"><summary className="cursor-pointer list-none text-lg font-black">{faq.question}</summary><p className="mt-4 max-w-3xl leading-7 text-slate-700">{faq.answer}</p></details>)}</div></div></section>
      <section className="px-5 py-24 lg:px-8 lg:py-36" style={{ background: palette.accent, color: '#fff' }}><div className="mx-auto flex max-w-7xl flex-col justify-between gap-10 md:flex-row md:items-end"><div className="max-w-3xl"><p className="text-xs font-black uppercase tracking-[.24em] text-white/75">Serve assistenza?</p><h2 className="mt-4 text-5xl font-black tracking-[-.06em] sm:text-7xl">Il veicolo è fermo a {city}?</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-white/90">Raccontaci cosa è successo e dove ti trovi. Organizziamo il passaggio successivo con un mezzo adatto e una destinazione concordata.</p></div><Call palette={palette} light>Chiama {site.phone}</Call></div></section>
    </main>
    <footer className="border-t border-black/10 bg-white px-5 py-10 lg:px-8"><div className="mx-auto grid max-w-7xl gap-8 md:grid-cols-[1fr_auto_auto] md:items-end"><div><strong>{site.name}</strong><p className="mt-2 max-w-md text-sm leading-6 text-slate-600">Soccorso stradale, recupero e trasporto veicoli con assistenza chiara sul territorio di {city}.</p></div><div className="text-sm text-slate-600"><p>{site.address}</p><p className="mt-1">{site.email}</p></div><Link href={`tel:${site.tel}`} className="text-lg font-black" style={{ color: palette.accent }}>{site.phone}</Link></div></footer>
  </div>
}
