import Link from 'next/link'
import { Container } from '@/components/Container'
import { ConsentBanner } from '@/components/ConsentBanner'
import { faqs, services, site, zones } from '@/data/site'

const accents: Record<string, string> = { salient: '#b42318', studio: '#0f766e', keynote: '#1d4ed8', spotlight: '#7c3aed', transmit: '#c2410c', primer: '#0369a1', protocol: '#be123c', pocket: '#111827', syntax: '#047857', catalyst: '#a16207' }
const accent = accents[site.template] || accents.salient
const image = '/images/home-hero.jpg'

function Phone({ label = 'Chiama ora', light = false }: { label?: string; light?: boolean }) {
  return <Link href={`tel:${site.tel}`} className={`inline-flex min-h-12 items-center justify-center rounded-lg px-5 py-3 text-sm font-extrabold transition hover:-translate-y-0.5 ${light ? 'bg-white text-slate-950' : 'text-white'}`} style={light ? undefined : { background: accent, boxShadow: `0 12px 26px ${accent}35` }}>{label}</Link>
}

function Nav() {
  return <header className="border-b border-slate-200 bg-white"><Container className="flex min-h-[74px] items-center justify-between gap-6"><Link href="/" className="text-sm font-black uppercase tracking-[0.14em] text-slate-950">{site.name}</Link><nav className="hidden items-center gap-7 text-sm font-bold text-slate-600 md:flex"><a href="#servizi">Servizi</a><a href="#zone">Zone servite</a><a href="#faq">Domande frequenti</a></nav><Phone label={site.phone} /></Container></header>
}

function HeroImage({ className = '' }: { className?: string }) { return <img src={image} alt={`Carroattrezzi in intervento a ${site.city}`} className={`h-full w-full object-cover ${className}`} /> }
function Services({ dense = false }: { dense?: boolean }) { return <section id="servizi" className="bg-white py-20 sm:py-28"><Container><div className="mb-12 max-w-2xl"><p className="text-xs font-black uppercase tracking-[0.22em]" style={{ color: accent }}>Interventi concreti</p><h2 className="mt-4 text-4xl font-black tracking-[-0.05em] text-slate-950 sm:text-6xl">Un aiuto preciso quando il veicolo non riparte.</h2></div><div className={dense ? 'grid gap-3 md:grid-cols-2' : 'grid gap-5 md:grid-cols-2 lg:grid-cols-3'}>{services.map((s, i) => <Link key={s.slug} href={`/servizi/${s.slug}/`} className="group border border-slate-200 bg-slate-50 p-6 transition hover:-translate-y-1 hover:bg-white hover:shadow-xl"><div className="mb-6 flex items-center justify-between"><span className="text-xs font-black" style={{ color: accent }}>0{i + 1}</span><span className="text-slate-400 transition group-hover:translate-x-1">↗</span></div><h3 className="text-xl font-black text-slate-950">{s.title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{s.text}</p></Link>)}</div></Container></section> }
function Zones() { return <section id="zone" className="bg-slate-950 py-20 text-white sm:py-28"><Container><div className="grid gap-12 lg:grid-cols-[0.7fr_1.3fr]"><div><p className="text-xs font-black uppercase tracking-[0.22em] text-amber-300">Presenza locale</p><h2 className="mt-4 text-4xl font-black tracking-[-0.05em] sm:text-6xl">{site.city} e i comuni vicini.</h2><p className="mt-6 max-w-md text-lg leading-8 text-slate-300">Conosciamo collegamenti, accessi e strade della zona. Apri la pagina della tua località e contattaci per organizzare il recupero.</p></div><div className="grid gap-x-8 sm:grid-cols-2">{zones.map(z => <Link key={z.slug} href={`/zone/${z.slug}/`} className="flex items-center justify-between border-b border-white/20 py-4 font-bold text-white transition hover:border-amber-300"><span>{z.name}</span><span className="text-slate-400">↗</span></Link>)}</div></div></Container></section> }
function Faq() { return <section id="faq" className="bg-white py-20 sm:py-28"><Container className="max-w-4xl"><p className="text-center text-xs font-black uppercase tracking-[0.22em]" style={{ color: accent }}>Risposte chiare</p><h2 className="mt-4 text-center text-4xl font-black tracking-[-0.05em] text-slate-950 sm:text-6xl">Prima di chiamare, ecco cosa sapere.</h2><div className="mt-12 divide-y divide-slate-200 border-y border-slate-200">{faqs.map(f => <details key={f.question} className="py-6"><summary className="cursor-pointer list-none text-lg font-black text-slate-950">{f.question}</summary><p className="mt-4 max-w-3xl text-base leading-7 text-slate-600">{f.answer}</p></details>)}</div></Container></section> }
function Cta() { return <section className="py-20 sm:py-28" style={{ background: accent }}><Container className="text-center"><h2 className="text-4xl font-black tracking-[-0.04em] text-white sm:text-6xl">Il veicolo è fermo?</h2><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-white/90">Raccontaci dove ti trovi e cosa è successo. Ti aiutiamo a individuare il prossimo passo con parole semplici e senza passaggi inutili.</p><div className="mt-8"><Phone label={`Chiama ${site.phone}`} light /></div></Container></section> }

function SimpleLight() { return <><section className="bg-white py-20 sm:py-28"><Container className="text-center"><p className="text-xs font-black uppercase tracking-[0.28em]" style={{ color: accent }}>Soccorso stradale {site.city}</p><h1 className="mx-auto mt-6 max-w-5xl text-5xl font-black tracking-[-0.07em] text-slate-950 sm:text-8xl">Carroattrezzi a {site.city}</h1><p className="mx-auto mt-7 max-w-2xl text-lg leading-8 text-slate-600">Quando il tuo veicolo non può proseguire, organizziamo traino, recupero e trasporto con una risposta chiara e una destinazione concordata.</p><div className="mt-8"><Phone /><Link href="#servizi" className="ml-3 inline-flex min-h-12 items-center px-5 py-3 text-sm font-bold text-slate-700">Vedi i servizi</Link></div><div className="mx-auto mt-16 max-w-5xl overflow-hidden rounded-3xl shadow-2xl"><div className="h-[360px] sm:h-[520px]"><HeroImage /></div></div></Container></section><Services /><Zones /><Faq /><Cta /></> }
function SendIt() { return <><section className="bg-[#0d0e11] px-5 py-20 text-white sm:py-28"><div className="mx-auto max-w-6xl text-center"><div className="mb-6 text-sm font-bold text-slate-300">★★★★★ <span className="ml-2 text-slate-500">Assistenza locale affidabile</span></div><h1 className="text-5xl font-semibold tracking-[-0.07em] sm:text-8xl">Carroattrezzi a {site.city}</h1><p className="mx-auto mt-7 max-w-2xl text-xl leading-8 text-slate-300">Un solo contatto per togliere il veicolo dalla difficoltà e portarlo dove serve.</p><div className="mt-8"><Phone /></div><div className="mx-auto mt-16 max-w-5xl overflow-hidden rounded-2xl shadow-2xl"><div className="h-[300px] sm:h-[470px]"><HeroImage /></div></div></div></section><section className="bg-[#f6f7fa] py-20"><Container><h2 className="text-center text-4xl font-black text-slate-950 sm:text-6xl">Assistenza senza passaggi complicati</h2><div className="mt-12 grid gap-5 md:grid-cols-3">{['Posizione chiara', 'Mezzo adatto', 'Destinazione concordata'].map((t, i) => <div key={t} className="rounded-3xl bg-white p-8"><span className="text-4xl font-black" style={{ color: accent }}>0{i + 1}</span><h3 className="mt-8 text-xl font-black text-slate-950">{t}</h3><p className="mt-3 text-sm leading-7 text-slate-600">Raccogliamo le informazioni essenziali e trasformiamo la richiesta in un intervento concreto per {site.city}.</p></div>)}</div></Container></section><Services dense /><Zones /><Faq /><Cta /></> }
function Landwind() { return <><section className="bg-slate-50 py-16 sm:py-24"><Container><div className="grid gap-12 lg:grid-cols-12 lg:items-center"><div className="lg:col-span-7"><p className="text-sm font-bold uppercase tracking-[0.18em]" style={{ color: accent }}>Servizio attivo 24 ore</p><h1 className="mt-5 text-5xl font-extrabold leading-tight tracking-[-0.06em] text-slate-950 sm:text-8xl">Soccorso stradale a {site.city}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-600">Dalla batteria scarica al recupero dopo un incidente, valutiamo la situazione e organizziamo l’intervento più adatto al mezzo.</p><div className="mt-8"><Phone label="Richiedi assistenza" /></div></div><div className="lg:col-span-5"><div className="overflow-hidden rounded-2xl bg-white p-3 shadow-xl"><div className="h-[390px] overflow-hidden rounded-xl"><HeroImage /></div></div></div></div></Container></section><Services /><section className="bg-slate-50 py-20"><Container><div className="grid gap-5 md:grid-cols-3">{['Arrivi più preparato', 'Parli con chiarezza', 'Porti il mezzo dove serve'].map(t => <div key={t} className="border border-slate-200 bg-white p-7"><h3 className="text-xl font-black text-slate-950">{t}</h3><p className="mt-3 text-sm leading-7 text-slate-600">Ogni passaggio viene spiegato prima, con attenzione a sicurezza, accessi e destinazione.</p></div>)}</div></Container></section><Zones /><Faq /><Cta /></> }
function Rainblur() { return <><section className="m-3 min-h-[720px] bg-slate-900 py-16 text-white sm:m-6 sm:py-24"><Container><div className="grid gap-12 lg:grid-cols-[0.9fr_1.1fr] lg:items-center"><div><p className="text-sm font-bold text-sky-300">Intervento locale, risposta diretta</p><h1 className="mt-5 text-5xl font-bold leading-tight tracking-[-0.06em] sm:text-8xl">Carroattrezzi a <span className="text-sky-300">{site.city}</span></h1><p className="mt-7 max-w-xl text-xl leading-8 text-slate-300">Se l’auto si ferma, puoi contare su un servizio pensato per recuperare il mezzo e ridurre l’incertezza.</p><div className="mt-8"><Phone label="Chiama subito" /></div></div><div className="overflow-hidden rounded-2xl border border-white/10 p-3"><div className="h-[390px] overflow-hidden rounded-xl"><HeroImage /></div></div></div></Container></section><Services /><Zones /><Faq /><Cta /></> }
function Nextly() { return <><section className="bg-slate-950 py-16 text-white sm:py-24"><Container><div className="mx-auto max-w-4xl text-center"><p className="text-sm font-bold text-cyan-300">Mobilità ferma? Ripartiamo da qui.</p><h1 className="mt-6 text-5xl font-black tracking-[-0.07em] sm:text-8xl">Carroattrezzi a {site.city}, senza incertezze.</h1><p className="mx-auto mt-7 max-w-2xl text-lg leading-8 text-slate-300">Una richiesta chiara, una valutazione attenta e un intervento organizzato per auto, moto e veicoli commerciali.</p><div className="mt-8"><Phone label="Parla con un incaricato" /></div></div><div className="mx-auto mt-16 max-w-6xl overflow-hidden rounded-3xl border border-white/10"><div className="h-[330px] sm:h-[520px]"><HeroImage /></div></div></Container></section><section className="bg-white py-20"><Container><div className="mx-auto grid max-w-5xl gap-8 md:grid-cols-3">{['Capire il problema', 'Scegliere il recupero', 'Rimettere ordine'].map((t, i) => <div key={t} className="border-t-4 pt-6" style={{ borderColor: accent }}><span className="text-sm font-black text-slate-400">0{i + 1}</span><h2 className="mt-5 text-2xl font-black text-slate-950">{t}</h2><p className="mt-3 text-sm leading-7 text-slate-600">Ti accompagniamo con indicazioni pratiche e una comunicazione comprensibile.</p></div>)}</div></Container></section><Services /><Zones /><Faq /><Cta /></> }
function Editorial() { return <><section className="bg-white py-20 sm:py-32"><Container><div className="grid gap-10 lg:grid-cols-12"><div className="lg:col-span-8"><p className="text-xs font-black uppercase tracking-[0.3em]" style={{ color: accent }}>Centrale operativa</p><h1 className="mt-6 text-6xl font-black leading-[0.92] tracking-[-0.08em] text-slate-950 sm:text-9xl">Carroattrezzi<br /><span style={{ color: accent }}>a {site.city}</span></h1></div><div className="flex items-end lg:col-span-4"><p className="text-xl leading-8 text-slate-600">Il recupero non è solo spostare un’auto: è rendere semplice una situazione che semplice non è.</p></div></div><div className="mt-14 grid gap-5 lg:grid-cols-[1.5fr_0.5fr]"><div className="h-[350px] overflow-hidden sm:h-[540px]"><HeroImage /></div><div className="flex flex-col justify-between bg-slate-950 p-8 text-white"><p className="text-5xl font-black">24H</p><p className="text-lg leading-8 text-slate-300">Per guasti, incidenti, recuperi e trasporti in città e provincia.</p><Phone label="Chiama ora" /></div></div></Container></section><Services /><Zones /><Faq /><Cta /></> }
function Protocol() { return <><section className="bg-rose-50 py-16 sm:py-24"><Container><div className="grid gap-12 lg:grid-cols-[0.28fr_0.72fr] lg:items-center"><div className="border-l-8 py-5 pl-6" style={{ borderColor: accent }}><p className="text-sm font-black uppercase tracking-[0.2em]" style={{ color: accent }}>Metodo chiaro</p><p className="mt-4 text-sm leading-7 text-slate-600">Posizione, veicolo e destinazione vengono chiariti prima del recupero.</p></div><div><h1 className="text-5xl font-black tracking-[-0.07em] text-slate-950 sm:text-8xl">Soccorso stradale a {site.city}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-700">Quando il mezzo è fermo, serve un intervento ordinato: raccogliamo il problema, valutiamo accessi e condizioni, poi concordiamo il trasporto.</p><div className="mt-8"><Phone label="Chiama subito" /></div></div></div></Container></section><Zones /><Services dense /><Faq /><Cta /></> }
function Pocket() { return <><section className="bg-slate-950 py-10 text-white sm:py-16"><Container><div className="grid gap-10 lg:grid-cols-2 lg:items-center"><div><div className="mb-7 flex items-center gap-3 text-sm font-bold text-slate-300"><span className="h-2 w-2 rounded-full" style={{ background: accent }} />Disponibili a {site.city}</div><h1 className="text-5xl font-black tracking-[-0.06em] sm:text-8xl">Carroattrezzi a {site.city}</h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-300">Un contatto rapido per liberare la strada e portare il veicolo in officina, carrozzeria o nel luogo concordato.</p><div className="mt-8"><Phone label="Chiama ora" /></div></div><div className="overflow-hidden rounded-[2rem] border border-white/10 p-3"><div className="h-[390px] overflow-hidden rounded-3xl"><HeroImage /></div></div></div></Container></section><Services dense /><section className="bg-slate-50 py-20"><Container><div className="max-w-2xl"><p className="text-xs font-black uppercase tracking-[0.2em]" style={{ color: accent }}>La differenza</p><h2 className="mt-4 text-4xl font-black tracking-[-0.05em] text-slate-950 sm:text-6xl">Una risposta concreta, dal primo contatto.</h2></div></Container></section><Zones /><Faq /><Cta /></> }
function Syntax() { return <><section className="bg-emerald-50 py-16 sm:py-24"><Container><div className="grid gap-10 lg:grid-cols-[1fr_0.85fr] lg:items-end"><div><p className="font-mono text-sm font-bold" style={{ color: accent }}>{`// soccorso_locale: ${site.city.toLowerCase()}`}</p><h1 className="mt-5 text-5xl font-black tracking-[-0.08em] text-slate-950 sm:text-9xl">Carroattrezzi a {site.city}</h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-700">Dove sei, quale mezzo è fermo e quale aiuto serve: partiamo da qui per organizzare il recupero.</p><div className="mt-8"><Phone label="Apri il contatto" /></div></div><div className="border border-emerald-200 bg-white p-3 shadow-xl"><div className="h-[330px] overflow-hidden"><HeroImage /></div><p className="p-4 font-mono text-xs text-slate-500">status: richiesta pronta</p></div></div></Container></section><Services /><section className="bg-slate-950 py-20 text-white"><Container><div className="grid gap-8 md:grid-cols-3">{['Posizione', 'Veicolo', 'Destinazione'].map(t => <div key={t} className="border-t border-emerald-300 pt-6"><h2 className="text-2xl font-black">{t}</h2><p className="mt-3 text-sm leading-7 text-slate-300">Informazioni utili per preparare un intervento adeguato.</p></div>)}</div></Container></section><Zones /><Faq /><Cta /></> }
function Catalyst() { return <><section className="bg-amber-50 py-16 sm:py-24"><Container><div className="mx-auto grid max-w-6xl gap-8 rounded-[2.5rem] border border-amber-200 bg-white p-7 shadow-xl sm:p-12 lg:grid-cols-[1.1fr_0.9fr] lg:items-center"><div><p className="text-xs font-black uppercase tracking-[0.25em]" style={{ color: accent }}>Centrale di soccorso {site.city}</p><h1 className="mt-6 text-5xl font-black tracking-[-0.07em] text-slate-950 sm:text-8xl">Carroattrezzi a {site.city}</h1><p className="mt-7 text-lg leading-8 text-slate-700">Se il veicolo è fermo, ti aiutiamo a capire il prossimo passo e organizziamo il recupero in modo sicuro e trasparente.</p><div className="mt-8"><Phone label="Richiedi un intervento" /></div></div><div className="h-[320px] overflow-hidden rounded-[2rem]"><HeroImage /></div></div></Container></section><Zones /><Services /><section className="bg-white py-20"><Container><div className="mx-auto max-w-3xl text-center"><h2 className="text-4xl font-black tracking-[-0.05em] text-slate-950 sm:text-6xl">Quando serve, sai già chi chiamare.</h2><p className="mt-6 text-lg leading-8 text-slate-600">Una comunicazione chiara riduce attese, passaggi e incertezze.</p></div></Container></section><Faq /><Cta /></> }

export default function TailAwesomeDemoHome() {
  const layouts: Record<string, () => React.ReactNode> = { salient: SimpleLight, studio: SimpleLight, keynote: Editorial, spotlight: Rainblur, transmit: SendIt, primer: Landwind, protocol: Protocol, pocket: Pocket, syntax: Syntax, catalyst: Catalyst }
  const Layout = layouts[site.template] || SimpleLight
  return <div className="site-shell"><Nav /><main><Layout /></main><footer className="border-t border-slate-200 bg-white py-10"><Container className="flex flex-col justify-between gap-5 text-sm text-slate-500 sm:flex-row"><div><strong className="text-slate-950">{site.name}</strong><p className="mt-2">{site.address}</p><p className="mt-1">{site.email}</p></div><Link href={`tel:${site.tel}`} className="font-black" style={{ color: accent }}>{site.phone}</Link></Container></footer><Link href={`tel:${site.tel}`} className="fixed bottom-4 right-4 z-40 rounded-full px-5 py-3 text-sm font-black text-white shadow-xl" style={{ background: accent }}>Chiama</Link><ConsentBanner /></div>
}
